
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mio.compiler.parser;

/** CUP generated class containing symbol constants. */
public class EstructuraParserSym {
  /* terminals */
  public static final int LBRACE = 4;
  public static final int ESTRUCTURA = 2;
  public static final int EOF = 0;
  public static final int CLAVE = 6;
  public static final int DIAGONAL = 8;
  public static final int error = 1;
  public static final int TABLA = 3;
  public static final int RBRACE = 5;
  public static final int NAME = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESTRUCTURA",
  "TABLA",
  "LBRACE",
  "RBRACE",
  "CLAVE",
  "NAME",
  "DIAGONAL"
  };
}

